# Use the official nginx image based on Alpine Linux
FROM nginx:alpine

# Copy all files from the current directory (.) to the default Nginx document root (/usr/share/nginx/html)
COPY . /usr/share/nginx/html

# The following lines are comments and explain how to build and push the image
# 1. Build the image for the linux/amd64 platform (replace with your target platform if needed)
#sudo docker build . -t plantafront:0.01

# 2. Push the built image to the specified registry (replace with your actual registry details)
# docker push europe-southwest1-docker.pkg.dev/mdona-cloud-lab-iconocer/aiinfra/recibof:0.02
